from mcpi.minecraft import Minecraft
import time

mc = Minecraft.create()
Pos = mc.player.getPos()
# mc.setBlock(Pos.x,Pos.y+2,Pos.z,145)
# mc.setBlock(Pos.x,Pos.y+2,Pos.z,145)
# mc.setBlock(Pos.x,Pos.y+2,Pos.z,145)
# mc.setBlock(Pos.x,Pos.y+2,Pos.z,145)
# mc.setBlock(Pos.x,Pos.y+2,Pos.z,145)
# mc.setBlock(Pos.x,Pos.y+2,Pos.z,145)

#mc.setBlock(Pos.x,Pos.y,Pos.z,47)

#mc.setBlock(Pos.x+2,Pos.y,Pos.z,47)
#mc.setBlock(Pos.x+2,Pos.y,Pos.z,47)

# mc.setBlock(Pos.x, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+1, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+2, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+3, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+4, Pos.z,47)
# mc.setBlock(Pos.x+1, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x+1, Pos.y+4, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y+4, Pos.z,47)
# mc.setBlock(Pos.x+1, Pos.y+2, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y+2, Pos.z,47)

# mc.setBlock(Pos.x, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+1, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+2, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+3, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+4, Pos.z,47)
# mc.setBlock(Pos.x+1, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x+1, Pos.y+4, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y+4, Pos.z,47)
# mc.setBlock(Pos.x+1, Pos.y+2, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y+2, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y+3, Pos.z,46)

# mc.setBlock(Pos.x, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+1, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+2, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+3, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+4, Pos.z,47)
# mc.setBlock(Pos.x+1, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x+1, Pos.y+4, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y+4, Pos.z,47)
# mc.setBlock(Pos.x+1, Pos.y+2, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y+2, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y+3, Pos.z,46)
# mc.setBlock(Pos.x+2, Pos.y+1, Pos.z,46)

# mc.setBlock(Pos.x, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+1, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+2, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+3, Pos.z,47)
# mc.setBlock(Pos.x, Pos.y+4, Pos.z,47)
# mc.setBlock(Pos.x+1, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x+1, Pos.y+4, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y+4, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y+2, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y+3, Pos.z,46)
# mc.setBlock(Pos.x+2, Pos.y+1, Pos.z,46)

# mc.setBlock(Pos.x, Pos.y, Pos.z,49)
# mc.setBlock(Pos.x+1, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x+2, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x+3, Pos.y, Pos.z,47)
# mc.setBlock(Pos.x+3, Pos.y+1, Pos.z,48)
# mc.setBlock(Pos.x+3, Pos.y+2, Pos.z,47)
# mc.setBlock(Pos.x+3, Pos.y+3, Pos.z,46)
# mc.setBlock(Pos.x+2, Pos.y+3, Pos.z,46)
# mc.setBlock(Pos.x+1, Pos.y+3, Pos.z,46)
# mc.setBlock(Pos.x, Pos.y+3, Pos.z,46)
# mc.setBlock(Pos.x, Pos.y+4, Pos.z,48)
# mc.setBlock(Pos.x, Pos.y+5, Pos.z,48)
# mc.setBlock(Pos.x, Pos.y+6, Pos.z,48)
# mc.setBlock(Pos.x+1, Pos.y+6, Pos.z,46)
# mc.setBlock(Pos.x+2, Pos.y+6, Pos.z,46)
# mc.setBlock(Pos.x+3, Pos.y+6, Pos.z,46)
# mc.setBlock(Pos.x+5, Pos.y+1, Pos.z,46)
# mc.setBlock(Pos.x+5, Pos.y+2, Pos.z,46)
# mc.setBlock(Pos.x+5, Pos.y+3, Pos.z,46)
# mc.setBlock(Pos.x+5, Pos.y+4, Pos.z,46)
# mc.setBlock(Pos.x+5, Pos.y+5, Pos.z,46)
# mc.setBlock(Pos.x+5, Pos.y+6, Pos.z,46)

